import logo from './logo.svg';
import './App.css';
import { List } from 'react-virtualized';

function App() {

  let myArray = [
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "punch",
      type: "car",
      name: "Tata Punch",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago",
      type: "car",
      name: "Tata Tiago",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "altroz",
      type: "car",
      name: "Tata Altroz",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tigor-ev",
      type: "car",
      name: "Tata Tigor EV",
    },
    {
      brandName: "Tata",
      brandSlug: "tata",
      slug: "tiago-ev",
      type: "car",
      name: "Tata Tiago EV",
    },
  ];

  // Render a single row for each car
  const rowRenderer = ({ key, index, style }) => {
    return (
      <div key={key} style={style}>
        {myArray[index].name}
      </div>
    );
  };
  return (
    <div >
      <div className="container">
        <List className="card"
          width={300}                   // Width of the list
          height={400}                  // Height of the list
          rowCount={myArray.length}     // Total number of items
          rowHeight={35}                // Height of each row
          rowRenderer={rowRenderer}      // Function to render each row
        />
        {/* {
          myArray?.map((value, i) => {
            return <>
              <div className="card">
                <p>{value.brandName}</p>
              </div>
              
            </>
          })
        } */}
      </div>


    </div>
  );
}

export default App;
